### ISSUE TITLE
Retrying setup error

### ISSUE THREAD

**Issue by Scales82** [MvdDonk/brewfather#2]
My integration has stopped working for some reason. Only shows this screen

![image](https://user-images.githubusercontent.com/44252921/218881707-ffc95267-a12c-4e36-b274-d3712db36847.png)

I have tried starting from scratch and no good.

**Comment by MvdDonk** [comment]
Hi, is this a problem with a existing integration or are you trying to setup a new connection?
Can you check the Home Assistant logs for Brewfather errors?

**Comment by Scales82** [comment]
This error originated from a custom integration.

Logger: custom_components.brewfather.coordinator
Source: custom_components/brewfather/models/batch_item.py:34
Integration: Brewfather batch information for Home Assistant (documentation, issues)
First occurred: 16 February 2023 at 17:02:06 (2980 occurrences)
Last logged: 12:32:55

Unexpected error fetching brewfather data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/brewfather/coordinator.py", line 54, in _async_update_data
    data = await self.update()
  File "/config/custom_components/brewfather/coordinator.py", line 66, in update
    await self.connection.get_batch(batch.id, DRY_RUN)
  File "/config/custom_components/brewfather/connection.py", line 63, in get_batch
    return batch_item_from_dict(json.loads(jsonText))
  File "/config/custom_components/brewfather/models/batch_item.py", line 285, in batch_item_from_dict
    return BatchItem.from_dict(s)
  File "/config/custom_components/brewfather/models/batch_item.py", line 261, in from_dict
    recipe = from_union([Recipe.from_dict, from_none], obj.get("recipe"))
  File "/config/custom_components/brewfather/models/batch_item.py", line 34, in from_union
    assert False
AssertionError

**Comment by Scales82** [comment]
![image](https://user-images.githubusercontent.com/44252921/219907335-6a2be428-a94f-4da9-a56d-1981688d1b66.png)

**Comment by MvdDonk** [comment]
Most likely this has to do with missing permissions in Brewfather. Make sure to enable the correct scope (see image below).
![image](https://user-images.githubusercontent.com/2156402/225591012-df589f9b-724a-4716-8110-25882bcb57a6.png)

If things still don't work please click "Enable debug logging" on the Brewfather integration and after a few minutes disable the logging "Disable debug logging". After disabling a log file will be downloaded, please send me the file or all Brewfather errors in the log.

Enable logging:
![image](https://user-images.githubusercontent.com/2156402/225591868-e9004589-c63b-437d-9531-422c6b0bee43.png)

Disable logging:
![image](https://user-images.githubusercontent.com/2156402/225591973-34ff7f07-a754-44bd-9650-cd808248e8ac.png)

**Comment by Scales82** [comment]
2023-10-30 12:07:45.205 ERROR (MainThread) [custom_components.brewfather.connection] Unable to create readings from json
2023-10-30 12:07:45.213 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Brewery for brewfather
Traceback (most recent call last):
  File "/config/custom_components/brewfather/connection.py", line 105, in get_readings
    reading = readings_from_dict(jsonData)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/models/reading_item.py", line 118, in readings_from_dict
    return from_list(Reading.from_dict, s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/models/reading_item.py", line 50, in from_list
    return [f(y) for y in x]
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/models/reading_item.py", line 50, in <listcomp>
    return [f(y) for y in x]
            ^^^^
  File "/config/custom_components/brewfather/models/reading_item.py", line 83, in from_dict
    rssi = from_union([from_int, from_none], obj.get("rssi"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/models/reading_item.py", line 30, in from_union
    assert False
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/__init__.py", line 45, in async_setup_entry
    await coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 53, in _async_update_data
    data = await self.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 64, in update
    readings = await self.connection.get_readings(batch.id, DRY_RUN)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/connection.py", line 108, in get_readings
    exit(1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 1

**Comment by Scales82** [comment]
That's the error I am getting, recreated the API key and checked scope, still no good.

**Comment by MvdDonk** [comment]
Which version of the integration are you using?
Can you enable debug logging, try again or wait until the error occurred, disable logging and attach the entire file here?
You can see how to enable debug logging in a few comments above this one.

**Comment by Scales82** [comment]
Version 1.1.4
File attached. Removed non-integration related data.
[home-assistant_brewfather_2023-11-02T23-45-30.747Z.log](https://github.com/MvdDonk/brewfather/files/13245646/home-assistant_brewfather_2023-11-02T23-45-30.747Z.log)

**Comment by MvdDonk** [comment]
@Scales82 
It doesn't seem debugging is enabled in the log file. I need to know what the JSON is that is returned by brewfather so I can see what's different in your situation.
When debugging is enabled you should see more logging, something like: "json response: [entire json here]"
You can see in my code here what is logged when debugging is enabled: https://github.com/MvdDonk/brewfather/blob/main/custom_components/brewfather/connection.py#L47

Please make sure debugging is enabled and also make sure your log file has the message "json response: [entire json here]" in it.
