### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by Scales82** [MvdDonk/brewfather#4]
This integration no longer works with my brewfather. Tried recreating it with a new API key and no luck. Stuck on retrying setup constantly.

**Comment by MvdDonk** [comment]
@Scales82 
Sorry to hear the integration setup is failing. I have just tested it myself and both an existing integration and adding a new one seems to work without issues.
Which version of Home Assistant are you running? 
Was the integration working before? 
Did it perhaps stopped working after a Home Assistant upgrade?

Maybe there is some information in the logs: https://my.home-assistant.io/redirect/logs/

Any more information can be helpfull, thanks!

**Comment by psychopenguin** [comment]
I'm getting the same errors.

`home-assistant-6c955d5577-wvgqn home-assistant 2023-10-02 10:48:27.010 ERROR (MainThread) [custom_components.brewfather.coordinator] Unexpected error fetching brewfather data:
home-assistant-6c955d5577-wvgqn home-assistant Traceback (most recent call last):
home-assistant-6c955d5577-wvgqn home-assistant   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
home-assistant-6c955d5577-wvgqn home-assistant     self.data = await self._async_update_data()
home-assistant-6c955d5577-wvgqn home-assistant                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/coordinator.py", line 53, in _async_update_data
home-assistant-6c955d5577-wvgqn home-assistant     data = await self.update()
home-assistant-6c955d5577-wvgqn home-assistant            ^^^^^^^^^^^^^^^^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/coordinator.py", line 59, in update
home-assistant-6c955d5577-wvgqn home-assistant     allBatches = await self.connection.get_batches(DRY_RUN)
home-assistant-6c955d5577-wvgqn home-assistant                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/connection.py", line 45, in get_batches
home-assistant-6c955d5577-wvgqn home-assistant     return batches_item_from_dict(json.loads(jsonText))
home-assistant-6c955d5577-wvgqn home-assistant            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/models/batches_item.py", line 114, in batches_item_from_dict
home-assistant-6c955d5577-wvgqn home-assistant     return from_list(BatchesItemElement.from_dict, s)
home-assistant-6c955d5577-wvgqn home-assistant            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/models/batches_item.py", line 54, in from_list
home-assistant-6c955d5577-wvgqn home-assistant     return [f(y) for y in x]
home-assistant-6c955d5577-wvgqn home-assistant            ^^^^^^^^^^^^^^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/models/batches_item.py", line 54, in <listcomp>
home-assistant-6c955d5577-wvgqn home-assistant     return [f(y) for y in x]
home-assistant-6c955d5577-wvgqn home-assistant             ^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/models/batches_item.py", line 91, in from_dict
home-assistant-6c955d5577-wvgqn home-assistant     name = from_union([Name, from_none], obj.get("name"))
home-assistant-6c955d5577-wvgqn home-assistant            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant-6c955d5577-wvgqn home-assistant   File "/config/custom_components/brewfather/models/batches_item.py", line 34, in from_union
home-assistant-6c955d5577-wvgqn home-assistant     assert False
home-assistant-6c955d5577-wvgqn home-assistant AssertionError`

**Comment by MvdDonk** [comment]
I finally found some time to look into the errors. Probably it has to do with some specific json response you are getting which I'm unable to reproduce. So for now I've added extra logging so hopefully I can reproduce the error and fix the problems.
If you can enable debug logging for the Brewfather integration, restart home assistant, disable debug logging and sent me the file I might be able to get more info on the issue. 
![image](https://github.com/MvdDonk/brewfather/assets/2156402/e5b740ac-7582-476b-bf81-bd79adedf498)

Please make sure you see some message like the following in the log file:
```
DEBUG (MainThread) [custom_components.brewfather.connection] get_batches https://api.brewfather.app/v2/batches/?status=Fermenting (False)
DEBUG (MainThread) [custom_components.brewfather.connection] get_batch https://api.brewfather.app/v2/batches/dpMXZzseP8PqbjG2VJjkC4p3LQwZ6S?include=recipe.fermentation,notes,measuredOg (False)
DEBUG (MainThread) [custom_components.brewfather.connection] get_readings https://api.brewfather.app/v2/batches/dpMXZzseP8PqbjG2VJjkC4p3LQwZ6S/readings (False)
``` 
If the log file does not have these lines in it you can try adding a new connection/running the setup:
![image](https://github.com/MvdDonk/brewfather/assets/2156402/3b4ab9c4-1738-4d54-9e38-8518f60139f6)

**Comment by psychopenguin** [comment]
Hi! Thanks for the update. I've tried with the new version and also noticed that you update to API v2. :)

But it still not working. Here are the debug logs:

```
2023-10-03 11:30:00.138 ERROR (MainThread) [custom_components.brewfather.connection] Unable to create batches from json
2023-10-03 11:30:00.153 ERROR (MainThread) [custom_components.brewfather.coordinator] Unexpected error fetching brewfather data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 53, in _async_update_data
    data = await self.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 62, in update
    for batch in allBatches:
TypeError: 'NoneType' object is not iterable
2023-10-03 11:31:01.167 DEBUG (MainThread) [custom_components.brewfather.coordinator] BrewfatherCoordinator._async_update_data!
2023-10-03 11:31:01.167 DEBUG (MainThread) [custom_components.brewfather.coordinator] BrewfatherCoordinator.update!
2023-10-03 11:31:01.167 DEBUG (MainThread) [custom_components.brewfather.connection] get_batches https://api.brewfather.app/v2/batches/?status=Fermenting (False)
2023-10-03 11:31:01.657 DEBUG (MainThread) [custom_components.brewfather.connection] json response: [{"_id":"wSpRtwMIrOmmGfuWFS1IdquwE0P1gE","batchNo":1,"brewDate":1696302000000,"brewer":"Fabio Brito d'Araujo e Oliveira","name":"Lote","recipe":{"name":"Summer Ale"},"status":"Fermenting"}]
2023-10-03 11:31:01.657 ERROR (MainThread) [custom_components.brewfather.connection] Unable to create batches from json
2023-10-03 11:31:01.676 ERROR (MainThread) [custom_components.brewfather.coordinator] Unexpected error fetching brewfather data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 53, in _async_update_data
    data = await self.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 62, in update
    for batch in allBatches:
TypeError: 'NoneType' object is not iterable
2023-10-03 11:31:01.698 DEBUG (MainThread) [custom_components.brewfather.coordinator] Finished fetching brewfather data in 0.531 seconds (success: False)
2023-10-03 11:31:01.698 WARNING (MainThread) [homeassistant.config_entries] Config entry 'brewfather' for brewfather integration not ready yet: None; Retrying in background
```

**Comment by MvdDonk** [comment]
@jeroenterheerdt can you update the Brewfather integration to the latest version (v1.1.2) and test again? If it's still not working please send me the logs.

**Comment by psychopenguin** [comment]
> It appears the Brewfather api returned a translated value for the word "Batch", which is "Lote" in Italian I assume? ;)

Actually, it's Portuguese :)

Well, I tried with v1.1.2 (and also the main branch) and it still doesn't work. I also put my BrewFather settings in English and create a new batch, without success. the logs are almost the same from previous version:

```
2023-10-03 14:46:27.568 WARNING (MainThread) [homeassistant.config_entries] Config entry 'brewfather' for brewfather integration not ready yet: None; Retrying in background
2023-10-03 14:46:32.897 DEBUG (MainThread) [custom_components.brewfather.coordinator] BrewfatherCoordinator._async_update_data!
2023-10-03 14:46:32.897 DEBUG (MainThread) [custom_components.brewfather.coordinator] BrewfatherCoordinator.update!
2023-10-03 14:46:32.897 DEBUG (MainThread) [custom_components.brewfather.connection] get_batches https://api.brewfather.app/v2/batches/?status=Fermenting (False)
2023-10-03 14:46:33.300 DEBUG (MainThread) [custom_components.brewfather.connection] json response: [{"_id":"3686bqe8RyyPPhF5wwURS6sKZdZgg7","batchNo":1,"brewDate":1696302000000,"brewer":"Fabio Brito d'Araujo e Oliveira","name":"Batch","recipe":{"name":"Summer Ale"},"status":"Fermenting"}]
2023-10-03 14:46:33.300 DEBUG (MainThread) [custom_components.brewfather.connection] get_batch https://api.brewfather.app/v2/batches/3686bqe8RyyPPhF5wwURS6sKZdZgg7?include=recipe.fermentation,notes,measuredOg (False)
2023-10-03 14:46:33.667 DEBUG (MainThread) [custom_components.brewfather.connection] json response: {"_id":"3686bqe8RyyPPhF5wwURS6sKZdZgg7","name":"Batch","batchNo":1,"status":"Fermenting","brewer":"Fabio","brewDate":1696302000000,"recipe":{"name":"Summer Ale","fermentation":{"hidden":false,"_created":{"_seconds":1696254715,"_nanoseconds":77000000},"_rev":"yxO8idPnNB5TPMEKPuRt9u56D4UFFj","name":"Summer Ale","_timestamp_ms":1696260544889,"_id":"iRLupEnvdiiF2UEE3VeBmGuLDyPMgB","_timestamp":{"_seconds":1696260544,"_nanoseconds":889000000},"steps":[{"actualTime":1696302000000,"stepTemp":20,"displayPressure":null,"ramp":null,"name":"Fermentacao","pressure":null,"displayStepTemp":20,"stepTime":7,"type":"Primary"},{"actualTime":1696906800000,"stepTemp":5,"displayPressure":null,"ramp":null,"name":"Maturacao","displayStepTemp":5,"pressure":null,"type":"Primary","stepTime":8},{"actualTime":1697598000000,"stepTemp":5,"displayPressure":null,"ramp":null,"name":"Clareamento","displayStepTemp":5,"pressure":null,"type":"Primary","stepTime":10},{"actualTime":1698462000000,"stepTemp":20,"displayPressure":null,"ramp":null,"name":"Envase","pressure":null,"displayStepTemp":20,"type":"Conditioning","stepTime":0.1},{"actualTime":1698462000000,"stepTemp":20,"displayPressure":null,"ramp":null,"name":"Carbonatacao","pressure":null,"displayStepTemp":20,"stepTime":10,"type":"Carbonation"}],"_version":"2.9.1"}},"notes":[{"note":"","type":"statusChanged","timestamp":1696337343524,"status":"Fermenting"}]}
2023-10-03 14:46:33.668 ERROR (MainThread) [custom_components.brewfather.connection] Unable to create batch from json
2023-10-03 14:46:33.688 DEBUG (MainThread) [custom_components.brewfather.connection] get_readings https://api.brewfather.app/v2/batches/3686bqe8RyyPPhF5wwURS6sKZdZgg7/readings (False)
2023-10-03 14:46:34.103 DEBUG (MainThread) [custom_components.brewfather.connection] json response: [{"temp":20,"sg":1.044,"comment":"","time":1696337345982,"id":"manual","type":"manual"},{"temp":20,"sg":1.04,"comment":"","time":1696337559802,"id":"manual","type":"manual"},{"temp":18,"sg":1.04,"comment":"","time":1696338085950,"id":"manual","type":"manual"}]
2023-10-03 14:46:34.104 ERROR (MainThread) [custom_components.brewfather.coordinator] Unexpected error fetching brewfather data: 'NoneType' object has no attribute 'readings'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 53, in _async_update_data
    data = await self.update()
           ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/coordinator.py", line 65, in update
    fermentingBatch.readings = readings
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'readings'
2023-10-03 14:46:34.138 DEBUG (MainThread) [custom_components.brewfather.coordinator] Finished fetching brewfather data in 1.242 seconds (success: False)
```

**Comment by psychopenguin** [comment]
Hey hey @MvdDonk 

I finally made it work. I found the issue was the wrong type for step_time parameter, as my recipes use some steps with decimal value, for example I put bottle as 0.1day. So I changed the type from int to float. I've opened a [pull request with the fix](https://github.com/MvdDonk/brewfather/pull/8).

Let me know when you merge and tag it then I can switch my HACS configuration to use your repo again. :) 

@jeroenterheerdt can you also see if this fix your issue?

Thanks!

**Comment by MvdDonk** [comment]
Hi @psychopenguin , thanks for helping with the issue. I actually just published a new version which contains the same fix (and other stuff) but I rewrote quite a bit of code. Can you try the latest version and let me know if that one works? If it does than I'll manually merge in your translation. Thanks for that bonus!!

**Comment by psychopenguin** [comment]
hi @MvdDonk thanks to accept the translation :)

i've tried this new version, but despite logs says the data was fetched successfully, sensors aren't being updated.

```
2023-10-04 10:41:49.105 DEBUG (MainThread) [custom_components.brewfather.coordinator] BrewfatherCoordinator._async_update_data!
2023-10-04 10:41:49.105 DEBUG (MainThread) [custom_components.brewfather.coordinator] BrewfatherCoordinator.update!
2023-10-04 10:41:49.105 DEBUG (MainThread) [custom_components.brewfather.connection] get_batches https://api.brewfather.app/v2/batches/?status=Fermenting (False)
2023-10-04 10:41:52.577 DEBUG (MainThread) [custom_components.brewfather.connection] json response: []
2023-10-04 10:41:52.579 DEBUG (MainThread) [custom_components.brewfather.coordinator] Finished fetching brewfather data in 3.474 seconds (success: True)
2023-10-04 10:41:52.579 DEBUG (MainThread) [custom_components.brewfather] Brewfather
2023-10-04 10:41:52.579 INFO (MainThread) [custom_components.brewfather] Setting up platform: sensor
2023-10-04 10:41:54.213 DEBUG (MainThread) [custom_components.brewfather.sensor] async_setup_entry
```

![image](https://github.com/MvdDonk/brewfather/assets/1420115/18e429bb-681c-47a0-958c-14ce344a05a4)

**Comment by MvdDonk** [comment]
Closing issue due to no response
